<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-7889H4F" failures="1" tests="6" name="Loan" time="0.113" errors="0" timestamp="2025-05-20T20:58:54 IST">
  <testcase classname="TestngPractice.Restudyone" name="busloan" time="0.008"/>
  <testcase classname="TestngPractice.Restudyone" name="vehicleloan" time="0.004"/>
  <testcase classname="TestngPractice.Restudyone" name="dummy" time="0.002"/>
  <testcase classname="TestngPractice.RestdThree" name="Creditcard" time="0.001"/>
  <testcase classname="TestngPractice.RestdThree" name="failuretest" time="0.008">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at TestngPractice.RestdThree.failuretest(RestdThree.java:44)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- failuretest -->
  <testcase classname="TestngPractice.Restudyone" name="carloan" time="0.001"/>
</testsuite> <!-- Loan -->
